simulation_config:
  random_seed: 2023

  top_in_at_random_shuffle:
    n_trials: 100000
    n_cards: 52
  
  riffle_shuffle:
    n_trials: 100000
    n_cards: 52
    max_riffle_shuffles: 15
  
  overhand_shuffle:
    n_trials: 5000
    n_cards: 52
    max_overhand_shuffles: 2800
    p: 0.25

  premo:
    n_trials: 100000
    max_riffle_shuffles: 10
    n_cards: 52